services:
  backend:
    container_name: backend
    build:
      context: "./server"
      dockerfile: Dockerfile.prod
    ports: 
      - "6002:7777"
    image: hmohammed2/taliba-match-backend:latest
    env_file:
      - ./server/.env.production
    environment:
      - NODE_ENV=production
  frontend:
    container_name: frontend
    build:
      context: "./client"
      dockerfile: Dockerfile.prod
    image: hmohammed2/taliba-match-frontend:latest
    env_file:
      - ./client/.env.production
    ports: 
      - "80:80"
    environment:
      - NODE_ENV=production
