services:
  backend:
    container_name: backend
    build:
      context: "./server"
      dockerfile: Dockerfile
    ports: 
      - "7777:7777"
    volumes:
      - ./server:/app/backend
      - /app/backend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongo
    command: npm run dev
  frontend:
    container_name: frontend
    build:
      context: "./client"
      dockerfile: Dockerfile
    ports: 
      - "5173:5173"
    volumes:
      - ./client:/app/frontend
      - /app/frontend/node_modules
    command: npm run dev
  mongo:
    image: mongo:latest
    container_name: mongo-server
    ports: 
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
volumes:
  mongo-data: