name: Deploy Production

on:
  push:
    branches: [ UAT ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create frontend env file
        run: echo "${{ secrets.FRONTEND_ENV_FILE_UAT }}" > ./client/.env.production
      
      - name: Create backend env file
        run: echo "${{ secrets.BACKEND_ENV_FILE_UAT }}" > ./server/.env.UAT

      # Build and deploy your containers
      - name: Build and push images
        run: docker compose -f docker-compose.uat.yml build && docker compose -f docker-compose.uat.yml push

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "Logged into VPS!"
            cd /docker_projects/talibah-test.ddns.net/
            docker compose up -d --build